### ISSUE TITLE
Arduino 1.6.4 throws error 

### ISSUE THREAD

**Issue by boblasure** [adamvr/arduino-base64#10]
C:\Users\user\Documents\Arduino\libraries\arduino-base64-master: Missing 'paragraph' from library

**Comment by Okadesde** [comment]
library.properties needs to be:

name=base64
version=1.0.0
author=Adam Rudd
maintainer=Adam Rudd
sentence=A base64 library for the arduino platform, written in C
paragraph=
category=Data Processing
url=https://github.com/adamvr/arduino-base64
architectures=*

**Comment by adamvr** [comment]
999595783185a0afcba156d7276dfeaa9cb5382f

Cheers!
