### ISSUE TITLE
I found a bug on library?

### ISSUE THREAD

**Issue by rtek1000** [adamvr/arduino-base64#20]
The library returns:

smtp.gmail.com = c210cC5nbWFpbC5jb20A

The https://www.base64encode.org/ returns:

smtp.gmail.com = c210cC5nbWFpbC5jb20=

I found a bug on library?

**Comment by palto42** [comment]
The library is ok, but there is an issue in the the example code, see my fix in pull request #23
and my https://github.com/adamvr/arduino-base64/issues/12#issuecomment-386869533

**Comment by rtek1000** [comment]
Thank you!
